# Generated by Django 6.1.1 on 2026-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Alex Morgan", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="AI/ML Architect & Backend Dev", max_length=200
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        default="Specializing in Deep Learning, LLM pipelines, and scalable architectures."
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "skills_list",
                    models.CharField(
                        default="Python, PyTorch, Django, React, TensorFlow",
                        max_length=300,
                    ),
                ),
            ],
        ),
    ]
