# Generated by Django 6.1.1 on 2026-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('aiml', 'AI / ML & Data Science'), ('backend', 'Backend & APIs'), ('frontend', 'Frontend & UI'), ('tools', 'DevOps & Tools')], default='aiml', max_length=20)),
                ('proficiency', models.IntegerField(default=85)),
            ],
        ),
    ]
